In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

In [12]:
df = pd.read_excel('/Users/tajveer/Desktop/IPL_team_followers.xlsx')
df

,Rankings,Teams,Total Followers,Brand Value (USD),Net Worth (₹ Crore)
0,1,Chennai Super Kings,44.8M,$235 million,"₹2,033 Cr"
1,2,Mumbai Indians,41.4M,$242 million,"₹2,094 Cr"
2,3,Royal Challengers Bengaluru,38.4M,$269 million,"₹2,327 Cr"
3,4,Kolkata Knight Riders,30.8M,$222 million,"₹1,918 Cr"
4,5,Punjab Kings,17M,$141 million,"₹1,219 Cr"
5,6,Delhi Capitals,16.5M,$152 million,"₹1,314 Cr"
6,7,Sunrisers Hyderabad,15.5M,$154 million,"₹1,331 Cr"
7,8,Rajasthan Royals,14.1M,$146 million,"₹1,262 Cr"
8,9,Gujarat Titans,7.6M,$142 million,"₹1,227 Cr"
9,10,Lucknow Super Giants,5.8M,$122 million,"₹1,054 Cr"

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Rankings             10 non-null     int64
 1   Teams                10 non-null     object
 2   Total Followers      10 non-null     object
 3   Brand Value (USD)    10 non-null     object
 4   Net Worth (₹ Crore)  10 non-null     object
dtypes: int64(1), object(4)
memory usage: 532.0+ bytes

In [14]:
#These are strings (text), not numbers — so I can’t analyze that properly!
df['Total Followers'] = df['Total Followers'].str.replace('M', '').astype(float)
df['Brand Value (USD)'] = df['Brand Value (USD)']\
    .str.replace('$', '')\
    .str.replace(' million', '')\
    .astype(float)

In [16]:
df['Net Worth (₹ Crore)'] = df['Net Worth (₹ Crore)']\
    .str.replace('₹', '')\
    .str.replace(',', '')\
    .str.replace(' Cr', '')\
    .astype(float)

In [17]:
df.columns = ['rank', 'team', 'followers_m', 'brand_value_usd_m', 'net_worth_cr']

In [19]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rank               10 non-null     int64
 1   team               10 non-null     object
 2   followers_m        10 non-null     float64
 3   brand_value_usd_m  10 non-null     float64
 4   net_worth_cr       10 non-null     float64
dtypes: float64(3), int64(1), object(1)
memory usage: 532.0+ bytes

,rank,team,followers_m,brand_value_usd_m,net_worth_cr
0,1,Chennai Super Kings,44.8,235.0,2033.0
1,2,Mumbai Indians,41.4,242.0,2094.0
2,3,Royal Challengers Bengaluru,38.4,269.0,2327.0
3,4,Kolkata Knight Riders,30.8,222.0,1918.0
4,5,Punjab Kings,17.0,141.0,1219.0